:sparkles: WFP-2259: added staff name data to initial appointment
ministryofjustice/hmpps-allocations pull request #454
Opened 2023-12-11 13:02 UTC by katie-cawthorne

2023-12-11 15:09 UTC, AndySweilam submitted a review, later dismissed
LGTM ⭐

2023-12-11 18:57 UTC, gregkhawkins requested changes

2023-12-11 18:57 UTC, gregkhawkins commented on src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsallocations/client/WorkforceAllocationsToDeliusApiClient.kt
> +  val name: Name?,
I can understand why `start` might be `null` and why that has been made nullable therefore but suspect that if there is a value for staff they will always have a name. Maybe we want to double check this with them but do not think we should be overly cautious or will end up with nullable everything.

Happy to chat on this though :)

2023-12-11 18:57 UTC, gregkhawkins commented on src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsallocations/client/WorkforceAllocationsToDeliusApiClient.kt
> +data class Name(val forename: String?, val middleName: String?, val surname: String?) {
same again with `forename` and `surname` unless you have seen examples with these being null. Perhaps we should just ask the question on these when we confirm their API is working fine. As they need us to confirm that with them anyway :)

2023-12-12 11:00 UTC, gregkhawkins submitted a review, later dismissed

2023-12-12 11:30 UTC, gregkhawkins approved these changes

2023-12-12 11:53 UTC, merged