WFP 2888 display restricted cases
ministryofjustice/hmpps-allocations pull request #557
Opened 2024-12-12 11:39 UTC by GaReid

2024-12-12 16:51 UTC, wood-n requested changes

2024-12-13 09:29 UTC, GaReid commented on src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsallocations/integration/unallocatedcases/GetCaseOverviewByCrnTests.kt
>    fun `get 404 if crn is restricted or excluded`() {
This was actually testing restricted only. I will rename it and will add tests for excluded only, restricted and excluded and neither for clarity

2024-12-13 10:30 UTC, GaReid commented on src/test/kotlin/uk/gov/justice/digital/hmpps/hmppsallocations/integration/unallocatedcases/GetUnallocatedCasesByTeamTests.kt
> +    workforceAllocationsToDelius.setApopUsers()
All the cases in this test are restricted. I will rename this. This test originally showed that restricted cases were not being included. This just shows the change of behaviour. 
**Get unallocated cases by team where probation-estate API is successful and cases have restrictions** test uses cases that are restricted, excluded, or both. I have commented for clarity

2025-01-06 12:44 UTC, sambailey-moj commented on src/main/kotlin/uk/gov/justice/digital/hmpps/hmppsallocations/service/UpsertUnallocatedCaseService.kt
>        log.info("Allocations receiving a non LAO case CRN, case case included: $crn")
typo - 'case case'

2025-01-06 13:06 UTC, sambailey-moj approved these changes

2025-01-07 12:44 UTC, merged